# Generated by Django 5.0.2 on 2024-03-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sazhnevapp', '0002_alter_client_phone_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(related_name='clients', to='sazhnevapp.product'),
        ),
    ]
